<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DS-PC" name="TestCases.ZigyCure.AddtoOrder" tests="1" failures="0" timestamp="13 Jul 2016 09:40:41 GMT" time="0.000" errors="1">
  <testcase name="testAdd2Order" time="0.000" classname="TestCases.ZigyCure.AddtoOrder">
    <error type="java.lang.Exception" message="TestCases.ZigyCure.AddtoOrder : Execution status is set to &#039;No&#039; in &#039;ExecutionChecker.xls&#039;">
      <![CDATA[java.lang.Exception: TestCases.ZigyCure.AddtoOrder : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.ZigyCure.AddtoOrder.ExecutionStatusCheck(AddtoOrder.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </error>
  </testcase> <!-- testAdd2Order -->
</testsuite> <!-- TestCases.ZigyCure.AddtoOrder -->
